name: Hubby
version: 2.2.1
author: github/rynstwrt
main: com.rynstwrt.hubby.Hubby


commands:

  spawn:
    permission: hubby.use
    description: Takes user to the spawn OF THE WORLD.
    usage: /<command>

  hubby:
    description: Used to reload the plugin's configuration.
    usage: §b[HUBBY] §a Did you mean "/<command> reload"?

  hub:
    aliases: [lobby, spawn]
    permission: hubby.use
    description: Takes a user to the spawn of a configurable main world.

  htp:
    permission: hubby.tp
    description: Teleports a player to a specified world.
    usage: §b[HUBBY] §a Did you mean "/<command> <playername> <world>" or "/<command> <world>"?


permissions:

  hubby.use:
    description: Allows for /spawn and /hub.

  hubby.reload:
    description: Allows for /hubby reload.

  hubby.bypass:
    description: Users with this permission are not teleported to the hub on join.

  hubby.tp.self:
    description: Allows a player to teleport themselves to a specified world.

  hubby.tp.others:
    description: Allows a user to teleport another player to a specified world.

  hubby.tp.*:

    description:

    children:
      hubby.tp.self: true
      hubby.tp.others: true

  hubby.*:

    description: Gives permission to all of Hubby's commands.

    children:
      hubby.use: true
      hubby.reload: true
      hubby.sethub: true
      hubby.tp.*: true