name: Hubby
version: 1.0
author: github/rynstwrt
main: com.rynstwrt.hubby.Hubby


commands:

  spawn:
    permission: hubby.use
    description: Takes user to the spawn OF THE WORLD.

  hubby:
    description: Used to reload the plugin's configuration.
    usage: /<command> reload

  hub:
    aliases: [lobby, spawn]
    permission: hubby.use
    description: Takes a user to the spawn of a configurable main world.

  htp:
    permission: hubby.tp
    description: Teleports a player to a specified world.


permissions:

  hubby.use:
    description: Allows for /spawn and /hub.
    default: true

  hubby.reload:
    description: Allows for /hubby reload.
    default: op

  hubby.bypass:
    description: Users with this permission are not teleported to the hub on join.
    default: op

  hubby.*:

    default: op
    description: Ability to reload the plugin and to use it.

    children:
      hubby.use: true
      hubby.reload: true
      hubby.sethub: true